name: CI
on: [ pull_request, push, workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-uid:
    name: Check Vial UIDs
    runs-on: ubuntu-latest

    steps:
    - name: (actions) Checkout Vial repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Verify Vial UID is unique per-keyboard
      run: python3 util/ci_vial_verify_uid.py
